on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - name: Get shortened version name
        run: |
          RELEASE_VERSION_SHORT=$(echo 0.5.1 | sed -nr 's/([0-9]+\.[0-9]).[0-9]/\1/p')
          echo "RELEASE_VERSION_SHORT=${RELEASE_VERSION_SHORT}" >> "$GITHUB_OUTPUT"
          mkdir test_folder
          echo "RELEASE_VERSION_SHORT=${RELEASE_VERSION_SHORT}" >> "test_folder/version"
        id: short_version
      - name: Deploy release documentation to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: test_folder
          target-folder: ${{steps.short_version.outputs.RELEASE_VERSION_SHORT}}
          single-commit: true