on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v4
      - name: Get release version
        run: |
          RELEASE_VERSION=$(git ls-remote --tags --sort=-'v:refname' https://github.com/scikit-activeml/scikit-activeml.git | head -n 1 | cut --delimiter='/' --fields=3)
      - name: Get shortened version name
        run: |
          RELEASE_VERSION_SHORT=$(echo $RELEASE_VERSION | sed -nr 's/([0-9]+\.[0-9]).[0-9]/\1/p')
          echo "RELEASE_VERSION_SHORT=${RELEASE_VERSION_SHORT}" >> "$GITHUB_OUTPUT"
          mkdir test_folder
          echo "RELEASE_VERSION_SHORT=${RELEASE_VERSION_SHORT}" >> "test_folder/version"
        id: short_version
      - name: Deploy release documentation to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: test_folder
          target-folder: latest
          single-commit: true
      - name: Deploy release documentation to Github Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: test_folder
          target-folder: ${{steps.short_version.outputs.RELEASE_VERSION_SHORT}}
          single-commit: true